### ISSUE TITLE
[task list][ml] Rare Variant Analysis Checklist

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#227]
**Background:**  We want a rare variant analysis module because much of the variance in rare disease incidence is explained by rare mutations. We want to create rare variant methods and use those in publications to push the field of genetics forward.

**Task List**:
- [ ] Get underlying statistical model for Dave's simulation written out
- [ ] Generate realistic simulations on Dave's 2 condition simulation
- [ ] Test the existing models (Reduced Rank Regression, EM ZIP TADA, ML TADA, Dirichlet Process TADA) on Dave's simulations, record performance
- [ ] Test the same models on our N+3 condition simulation and write down results
- [ ] PR Adversarial model: maximizes explained, minimizes predictive ability on confounding variables.
   - Stretch goal: get it reviewed and in.
- [ ] Share results with Dave & ask him for N condition simulator
