### ISSUE TITLE
Cut b11.0.0 release from master

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#25]
The master branch is a substantial improvement of the b10 codebase, including a new "nearest" track that uses a ahead-of-time de-duplication strategy to reduce disk space and improve annotation performance, and which allows the calculation distance to nearest features.

- Currently used to calculate nearest gene, nearest Tss distances (as well as list details about those genes/tss'), and to create a refSeq.gene track, which contains, pLi, pNull, pHI, lofTool, GDI, and more.

Furthermore, building now uses LMDB cursors, and is remarkably faster (build times are < 1/2 of b10).

###### TODOS

- [ ] Update all used annotations, esp gnomad.

- [ ] Finish CADD track test (double check if still needed, we may have all necessary tests)

- [ ] Modify all track tests (besides VCF, which has this done) to show that building from scrambled files when n > 1 files present works

- [ ] Implement overlap delimiter. This delimiter allow a n:m (m > n) relationships between fields within one track. The highest cardinality scalar vector within a given track determines the relationships. By convention this should be the first track. This is, in effect, the primary key. 
  - Example: one refSeq.name (by definition all refSeq entries are unique on name) may have multiple kgID's. This would be represented as name1;name2  \t kgIDforName1_1\kgIDforName1_2\kgIDforName1_3;kgIDforName2

- [ ] Decide on the names for nearest genes tracks (currently refSeq.nearest.* refSeq.nearestTss.*) and the refSeq.gene track (which holds gene-level rather than tx-level information overlapping refSeq transcripts...for instance pLi, pNull, etc)

- [ ] Change beanstalk workers, SeqElastic, SeqFromQuery to use supplied configuration files (search/maping and annotation YAML), rather than the corresponding assembly configuration found in config.
  - This is needed to help protect backward compatibility for a single annotation (re-indexing), and make better use of the state (configurations) stored alongside every annotation

- [ ] Make hg38-lifted-over CADD publicly available
  - This should probably be the filtered cadd, since this is far simpler to work with (sorted, bad sites removed)

- [ ] Update SeqElastic, SeqFromQuery to parse the new delimiter

- [ ] Update the front end to handle delimiter use

- [ ] Update changelog

- [ ] Switch clinvar to by-allele-matching, using McArthur lab clinvar vcf.
  - Decide whether to keep the existing clinvar overlap of refSeq

- [ ] * Add basic HGVS support

- [ ] * Update mapping files to support Elasticsearch 6. Namely, split_on_whitespace no longer works, so we need to use copy_to to move 

- [ ] ** Allow submission of any valid track type (vcf, .bed, nearest) to add custom annotations

"*" May be deferred for first minor (feature) release

** Likely to be deferred to 2nd (feature) release.

**Comment by akotlar** [comment]
I think this is a top priority. We need, in particular, to figure out a migration / communication strategy before actually releasing, so that existing users don't need to migrate their workflows.

cc @wingolab

**Comment by akotlar** [comment]
This is no longer relevant, we are working towards a 1.0 release
