### ISSUE TITLE
Annotation Sprint 2 Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#273]
### Background:
Improving Annotation for Maintainability

### Completion Criteria:
hg19 and hg38 database that has exact match for dbSNP and ClinVar, add back 'intergenic'

### Implementation Summary
- [x] Switch from using dbSNP tab separated to VCF file for exact match (tab separated gives no guarantee that allelic representation matches)
- [ ] Switch from using ClinVar tab separated to VCF file for exact match (tab separated gives no guarantee that allelic representation matches)
- [x] Ensure global regex's are applied to values being inserted into the database 
      - Every track will have to ensure that it applies the replacement method which will be defined in class Tracks::build
      - Document this
- [ ] Replace unit separator with forward slash
- [x] Write replacement unit tests for overlapping values

**Comment by akotlar** [comment]
See https://github.com/bystrogenomics/bystro/pull/304 and https://github.com/bystrogenomics/bystro/pull/300 for dbSNP 2 - related PRs.

I've tested building the resulting transformed file (100k lines), and that works well. For instance, querying chr1:10114, shows us the expected data, see attached

Expected features (these will be displayed in order, from index 0 to index 10 in the next image):
<img width="263" alt="Screenshot 2023-10-19 at 1 13 27 AM" src="https://github.com/bystrogenomics/bystro/assets/5543229/5f0b311e-cf27-4f6d-8adf-9ebb1bf4bb60">

The result in Bystro
<img width="299" alt="Screenshot 2023-10-19 at 1 12 58 AM" src="https://github.com/bystrogenomics/bystro/assets/5543229/2041d2a4-4ebb-41ed-bbc2-c83ffde8efd2">

The expected allele frequencies, per population
<img width="1250" alt="Screenshot 2023-10-19 at 1 14 56 AM" src="https://github.com/bystrogenomics/bystro/assets/5543229/55a39938-d944-4934-a54b-3a1d0251ecb5">

**Comment by akotlar** [comment]
"Write replacement unit tests for overlapping values" is already done, see 

"Ensure global regexes applied" is done, see:
- code: https://github.com/bystrogenomics/bystro/blob/master/perl/lib/Seq/Tracks/Build.pm#L199, which is applied by every track except CADD and Score, which deal only with numeric values: https://github.com/search?q=repo%3Abystrogenomics%2Fbystro%20coerceFeatureType&type=code
- tests: https://github.com/bystrogenomics/bystro/blob/master/perl/t/output/delimiters.t, https://github.com/bystrogenomics/bystro/blob/9d64609c44942f30ce7a21a1c4fd6d996fc808e9/perl/t/tracks/build/coerceFeatureType.t#L33

**Comment by cristinaetrv** [comment]
Remaining work moved to Sprint 3
