### ISSUE TITLE
Annotation Sprint 3 Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#302]
- [x] Switch from using ClinVar tab separated to VCF file for exact match (tab separated gives no guarantee that allelic representation matches)

- [x] Replace unit separator with forward slash, rebuild database with that in place

- [x] Add CADD indel scores

- [x] Remove position delimiter 

- [ ] #349
heterozygotes:(4805 && 1805) cadd > 20
and
heterozygotes:(4805 1805) cadd > 20 (no &&) work the same
Previously, in Elasticsearch 5.6 (b10), these were equivalent

- [x] Check for number of result deviation between && and no &&, and other issues
- [x] Update search/save handler to generate statistics and support statistical filters (https://github.com/bystrogenomics/bystro/issues/314)

**Comment by akotlar** [comment]
#343 , #344 , #345 , #346 , #347  close this ticket

The "Fix opensearch regression making" will need to wait for future sprint. Needs more investigation, we appear to be using the appropriate setting for setting spaces as "ands", and updating our query parser to fix any problems in Opensearch are outside this scope. There remains a possibility that there is a new setting that we have missed, and in sprint 4 I will investigate that.
