### ISSUE TITLE
PRS Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#313]
### PRS module
- [x] Documentation: Find/select 1 PRS module to implement/port
Sprint 7:
- [x] Stand up worker for PRS
- [x] Preprocess of genotype data (VCF or from annotation) for PRS as a dosage matrix
- [x] Ingest association scores for PRS using GIANT UMich format, we are planning to enforce this format for any incoming GWAS summary stats
- [x] Implement calculation of PRS (C+T)

Future goals;
- [ ] Ingest covariate information for PRS/GWAS
     - People may want to include PC's either from pre-calculate ancestry or from dataset alone

**Comment by cristinaetrv** [comment]
Update 2/9/24

- Was able to start testing with GIANT format files and converted everything to include that header
- Since GIANT files are in hg19, preprocessed 1kGP in hg19 which will also be useful for re-training/training Ancestry with hg19 (also tried ld pruning with multiple parameters and re-processed 1kGP in hg38 with those parameters for training Ancestry, added a plink sh script on the workstation in case this needs to be adjusted or run again)
- Dennis helped me get bystro-vcf running, and there are a couple important updates that need to be added to the README (I can PR this next week): 
`go get github.com/akotlar/bystro-vcf && go install $_; `
needs to change to
`go get github.com/bystrogenomics/bystro-vcf && go install $_;`
And this script doesn't build, so suggest adding 'go build' as well
- Got a feather dosage matrix file from 1kGP hg19 subset using bystro-vcf successfully
- Up next, converting pandas workflow to include arrow throughout, or maybe replace pandas completely (including the ancestry file coming in for genetic maps and the GWAS summary stats files)
- During meeting, we discussed adding a liftover step to the GWAS summary stats because it will probably be the case that GWAS summary stats are older (hg19) and user datasets will be newer (hg38) or vice versa, will add this to sprint 8 goals
- Still need to write tests for PRS code once everything is in the correct format, will try to do next week and get current workflow PR'd

**Comment by wingolab** [comment]
@cristinaetrv  - I got it to install with `go install github.com/bystrogenomics/bystro-vcf@latest`, which is the more idiomatic way of installing golang tools. It worked for me. Can you give it a try and, if it works for you, we could update the bystro-vcf repo README.

**Comment by cristinaetrv** [comment]
See continuation in Sprint 9 Task List, created issue for install instructions
