### ISSUE TITLE
IBD Genomics Consortium - Task List

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#326]
###### A concise description of why we're pursuing this task.
Dave Cutler's recommendations for stuff they would find meaningful, and which we should do our best to get in before end of January.

###### What is the goal, and how do we know this task is accomplished? 

- [ ] Add pLi and Loeuf scores for genes.  
- [ ] Add MPC scores for variants.
- [ ] Allow the user to upload a pedigree file with their VCF, and then output  the plink2 files directly, with the correct pedigree / 
sex / phenotype information, and the correct "names" (rs numbers when available,
and something natural like chr_position for variants with no rs number) for the
variants.  
- [ ] Add "SKAT" input to the plink data.  Basically let the user pick variant  criteria, and 
output lists of those variants broken down by gene... something like
that.... not redumping the whole VCF or annotations or plink files, but literally 
just variant lists by gene, readable by SKAT, where the user specified the criteria 
to make those lists.

- [ ] For ancestry stuff you should think about doing your graphical wizardry.
How about having a set of 1000 genome samples precomputed and including 
PC1 vs PC2,  PC1 vs PC3, and PC2 vs PC3 plots with all the samples included 
in the current VCF analysis... with current samples in a prominent color, and the public
samples labeled in a sort of light transparent-ish kinda color?  Can I click on 
points, and think about "flagging / excluding" them?   I could actually imagine 
replacing your tile plots on the front page with these PCA type plots. 
If the pedigree file had some standardized field for self-reported ancestry, you 
could even flag discrepancies between self-report and the apparent genetics.

- [ ] Along the lines of ancestry stuff, you could add checks for duplicates / close
relatives,  a sex check, etc, but Plink2 will do this plenty well, as is.

**Comment by akotlar** [comment]
cc @cristinaetrv
