### ISSUE TITLE
Sprint 4 - Alex Task List

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#348]
For GV demo:
- [ ] Open jupyter notebook, use python API to do same thing (fragpipe output using genetic annotation that you can download)
- [ ] Add ability to do proteomic regression (association testing) analysis

For end of Nov deployment:
- [x] Switch to bgzip w/indexing in place of pigz for parallel decompression
- [x] 2x+ indexing performance - either switch to Rust, or see if bgzip decompression in separate process brings enough performance gain
- [x] Switch output order, so that ref is right next to alt, not discordant

Stretch:
- [x] (stretch) Switch to Rust bystro-vcf w/ MNP linkage information & no limits on number of alleles in multi allelic line
- [ ] (stretch) Add pLi and Loeuf scores for genes, if possible with existing builders, else document strategy
- [ ] (stretch) Add MPC scores for variants, if possible with existing builders, else document strategy
- [ ] (stretch) Switch to Rust or Cython binomial map filter
- [ ] (stretch) https://github.com/bystrogenomics/bystro/issues/349

Organizational
- [x] Respond to Chris Tastad

**Comment by akotlar** [comment]
>  Switch to Rust bystro-vcf w/ MNP linkage information & no limits on number of alleles in multi allelic line

This was accomplished in the go implementation of bystro-vcf.

**Comment by cristinaetrv** [comment]
This Sprint has concluded
