### ISSUE TITLE
Cristina - Sprint 6 Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#372]
- [ ] #368 
- [ ] #369 
- [ ] #370 
- [ ] #371 
- [ ] Determine which features (regulatory) we could add to Bystro
- [ ] Look into gene ontology for proteomics
- [ ] Figure out where pLi and Loeuf scores for genes and MPC scores for variants could be acquired

**Comment by cristinaetrv** [comment]
This description of work updated in #313
