### ISSUE TITLE
Sprint 7 - Webapp Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#384]
- [x] Review webapp and document bugs found
- [x] Investigate beanstalkd jobs that disappear
- [x] Change output cards to list of structs to visually align outputs, necessary because current output doesn't show current version of the database
