### ISSUE TITLE
Sprint 7 - Ancestry Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#390]
- [ ] Containerize the Ancestry model for integration PoC
- [x] (stretch) hg19 version of model
- [x] 'Still generating results' message
