### ISSUE TITLE
Sprint 7 - Rare variant Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#391]
- [ ] Define realistic parameters for simulation
- [ ] Write out the model
- [ ] Implement a prototype of the model
- [ ] Research alternatives

I'm currently working on modifying the point of effect method developed by Dave and Mike Epstein to provide explicit parameter estimates. Will rely on exploiting inherent data characteristics. Also characterizing statistical power and size in high dimensions.
