### ISSUE TITLE
Sprint 9 Task List

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#421]
Webapp
- [x] Fix S3 upload  - March 13th for PR @akotlar 
- [x] Fix search cards to show all data - March 13th for PR @akotlar 
- [x] Hide settings wheel in queued file list (it is not currently enabled)  - March 11th @akotlar 
- [x] Autocomplete field names - March 15th @akotlar 
- [x] Fix search phase exception with long query: @akotlar noticed that an aggregations (Heterozygotes per variant  was cancelled after it ran for a certain amount of time). If cannot be solved, remove the offending aggregation scripts. https://github.com/bystrogenomics/bystro-web/issues/388 - @akotlar - March 28th
- [x] Finish making AMIs for bystro-web, bystro, and opensearch servers - hard deadline is March 29th.
- [x] (stretch) Add ability to rename genetic submissions in front end, before uploading them, by clicking on the name  -@akotlar 
- [x] (stretch) Add ability to stitch together datasets.
- [ ] (stretch) Add Jupyter notebook launcher
- [ ] (stretch) support (refSeq:brca1), which would expand to (refseq.\\*:brca1)
- [x] (stretch) Update numerical facets to allow selecting on ranges using slider

Annotation
- [x] Test hg19_v8 database by comparing results, row by row, on trio_trim.vcf.gz between hg19_v8 and dave's instance b10 database - March 15th @akotlar 
- [x] Create hg38 database - March 11th @akotlar 
- [x] Test hg38 database by comparing results, row by row, on trio_trim.vcf.gz between hg19_v8 and dave's instance b10 database - March 18th @akotlar 

Ancestry
- [x] Retrain ancestry model (hg38) with 76k gnomad loadings - @cristinaetrv  - March 13th
- [x] Liftover array set - @cristinaetrv - March 13th 
- [x] Liftover gnomad loadings - @cristinaetrv  - March 14th 
- [x] Add assembly to AncestryData, update bystro-web to submit assembly, and use assembly when choosing model (https://github.com/bystrogenomics/bystro/issues/419) - @akotlar - March 13th
- [x] Create ancestry docker container - @akotlar - March 14th
- [x] Add support for choosing best covariate set for ancestry - @akotlar - March 15th
- [x] Gives Thomas new ancestry code to test on healthy aging study - March 20th @cristinaetrv 
- [x] Add Ancestry table version that just has IDs and top hit superpops that can be expanded to larger table @akotlar 

- Before expanding, top hit for superpops is seen, after expanding format remains as before
- Possible format:  Sample ID | Top hit Superpop | Prob(Top hit superpop)  --> Expand to see: Number Variants retained| Prob of other Superpops (5 columns) | Prob of Population 1,2,3 ...
- For populations: Instead of adding all 26 populations as something you have to open for each one, add the columns as 'Prob(CEU), Prob(CDX)' and so on for each individual

- [x] Switch missingness to 'variants retained'

Proteomics Data Handling / API
- [ ] Finish download of proteomics data - March 12th @dlin30 
- [x] Fix frontend upload of proteomic data - March 13th @dlin30 
- [ ] Add support for somascan upload in bystro webapp and api - March 14th @akotlar 

Proteomics Statistics
- [ ] Jupyter notebook demonstrating adjusting for batch effects on Adverserial PPCA on simulation data + a real dataset (@akotlar) - March 14th @austinTalbot7241993 

Infrastructure
- [x] Make sure EBS scratch disk is very well provisioned, or use instance with 4TB SSD
- [x] Update bystro webapp documentation on how to use bystro, write API documentation, write library documentation - @akotlar - March 28th

PRS
- [x] Add AD GWAS summary statistics suggested by Thomas for C+T PRS - March 15th @cristinaetrv 
- [ ] Add readme for AD GWAS sum stats - March 18th @cristinaetrv -> Move to sprint 10
- [ ] Add batch processing for PRS C+T workflow - March 25th -> Move to sprint 10
- [ ] Finish PRS-CS standard way without Langevin Dynamics  - @austinTalbot7241993 -  March 28th.
- [ ] Add support for covariates into PRS - @cristinaetrv - March 25th -> Backlogged for now, move to sprint 11/12

POE
- [x] Mike Epstein was positive on Austin's POE method. Address Mike's simulation suggestions - March 28th

**Comment by akotlar** [comment]
S3 Uploads now work, even for very large datasets (e.g. 100GB+ uploads). 
bystro webapp documentation is updated, but I have not had a chance to add detailed library documentation

**Comment by akotlar** [comment]
Semi-automated AMIs have been made and deployed to IBDGC. They need 1 more pass of refinement in order to be fully capable of being taken down / up at will in autoscaling fashion, sprint 10 task
