### ISSUE TITLE
Sprint 11 Task List

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#456]
### General
- [x] Improve installation instructions so that the annotator can be installed without issue on Amazon Linux 2023 - @dlin30  - 2024/05/08

### Proteomics
Datasets: https://www.synapse.org/#!Synapse:syn53420674.1/datasets/, https://www.synapse.org/#!Synapse:syn31822992/wiki/617907

- [ ] Add support for somascan upload to bystro webapp @dlin30 - April 8/9 - Currently under review by @akotlar 
- [x] Add support for somascan upload through api - @akotlar - April 5th
- [x] Jupyter notebook demonstrating adjusting for batch effects Domain adaptation and imputation on neuroscience data, and in simulation - @austinTalbot7241993 
- [x] Jupyter notebook demonstrating adjusting for batch effects using Domain adaptation and imputation on ~300 samples TMT + SomaScan data - @akotlar - 2024-05-08
- [x] SPPCA version for low sample scenarios - @austinTalbot7241993 Ilha - 2024/05/08
- [ ] Generate network analysis results using SPPCA on ~300 sample dataset @akotlar - 2024/05/15
- [x] Improve protein abundance filtering using genetic data with the goal of 1) supporting any annotation features that Bystro outputs, (stretch) 2) outputting arrays of structs instead of struct of arrays for multi-field annotations that are requested @akotlar - 2024-05-10
- [ ] API endpoint to submit filtering prot jobs @dlin30 - 2024/05/06 for initial PR, 2024/05/08 for merged PR
- [x] Finish queue listener code v1 #434 @dlin30 - April 14

### PRS 
Goal for Sprint 11: Have a PRS C+T running through the webapp (with display of results in webapp potentially in sprint 12)
Provisional for Sprint 13: Have this deployed to IBDGC (we'll need information from them for what they'll find useful in terms of GWAS summary stats)

- [x] Add back in AD GWAS summary statistics for hg19 - 2024/05/06 for PR 
- [x] Add in LD map for clumping in hg38 - @cristinaetrv - 2024/05/06 for PR 
- [x] Optimizing PRS C+T for performance - @cristinaetrv  - 2024/05/06 for PR
- [ ] (sprint 12) Need annotation for ancestry in AD stat summary  - @cristinaetrv
- [ ] Add batch processing for PRS C+T workflow with dosage matrix for memory issues @cristinaetrv - @cristinaetrv  - 2024/05/08 for PR
- [ ] Automatically launch PRS after ancestry from API server - @akotlar - 2024/05/16 for PR

- [ ] (stretch) Take in ancestry PCs as PRS-CS covariates @austinTalbot7241993 @akotlar  - April 24
- [ ] (stetch) Take in top hit from ancestry, convert to superpop, connect to LD map for corresponding pop for LD clump / expectation is that we will at least have this in progress in sprint 11 @cristinaetrv - 2024/05/16
- [ ] (stretch) Add readme for AD GWAS sum stats  @cristinaetrv - 2024/05/16
- [ ] (stretch) Display basic PRS results in webapp (table with individuals and their score) - @akotlar -  2024/05/16

- [ ] (sprint 12) Finish PRS-CS standard way without Langevin Dynamics @austinTalbot7241993
- [ ] (sprint 12) Weigh PRS scores by gnomad allele frequencies for specific ancestries and the corresponding ancestry probability: `Beta*dosage - 2*( sum_over_superprop_ancestry { maf_gnomad_in_ancestry * p_ancestry } )` - TBD

Important to IBDGC (and likely other consortiums). 

### Covariance Matrix Estimation
Overall goal: is to improve network analysis, regressions, clustering, anything that relies on a covariance matrix, and the empirical covariance matrix is not a good estimator, especially in small sample sizes.

- [x] Incorporate singular value shrinkers - Ilha - 2024/05/08
- [x] Start testing performance of these shrinkers on gaussian data / rank 1 covariance matrices - Ilha - 2024/05/08
- [x] Implement a non-negative covariance matrix estimator, which will be useful for genetic methods where we can assume no negative correlations (like rare variant analysis) - Ilha - 2024/05/16

### Infrastructure
- [x] Improve Python wheels so that they're deployable on ARM Mac, X86 Mac, Linux - @akotlar - 2024/05/16 for ability to install on Mac.

### Post IBDGC Tasks
- [x] Improve saving performance - April 5th
- [x] (critical) Add ability to whitelist user accounts, accepting only environment-variable specified email addresses
- [x] Search as you type (16ms timeout) - "instant search" for more feedback when you don't know what to type
- [x] Search for fields in FIlters and Aggregations
- [ ] (sprint 13+) Re-runnable chunked uploads for both local and from-s3 uploads to handle network instability
- [ ] (sprint 13)(high) Add automated report generation for the highly consequential variants (with far fewer annotations) Toggle for less complex view, download that less complex field view 'Clinical report'
- [x] (sprint 12) Quick search buttons - "Clinical variants", "Deleterious Mutations" -  2024/05/16 to get initial mockup
- [ ] (sprint 13) Add click on table cells to copy query - TBD
- [ ] (sprint 14+) Make AMIs fully restartable, including bystro-annotator 
- [x] Kick tires on data sharing. IBDGC will be relying on Public/Share 
- [ ] (sprint 13+) Improve data sharing - give permissions for individual samples and variants - @akotlar 
- [ ] (sprint 13+) Add vcfAlt and vcfRef annotations (the original ref / alt? or after normalization? if the latter, then vcfPos has to change to the normalized position) (Data management)
- [x] (stretch) Autocomplete field queries (May be pushed to Sprint 11)
- [ ] (After summer) Share custom synonyms (IBDGC really liked this)
- [x] Add deletion 'Are you sure' button
- [x] Fix refreshing of search page when ancestry isn't completed yet
- [x] New upload system - upload files from s3 in the background

**Comment by cristinaetrv** [comment]
Notes on "Add automated report generation for the highly consequential variants (with far fewer annotations"
  - Gene name, clinvar, exonicAlelleFunction, siteType, cadd, sampleMaf, gnonomad.genomes/exomes.AF, gnomad.genomes/exomes id, amino acid substitution, codon number
  - VEP-like CONSEQUENCE - add that
    - most severe and canonical - just the most severe

Needs to be easily digestible - either a saved subset of the full, 
- the processing will be done by an analyst, the end user (Judy) will need to be very digestible

**Comment by akotlar** [comment]
# 2024-04-23

## Proteomics Topic Meeting
Austin:
- Domain adaptation, and we need complete data, so we need to impute missing values; the 330 TMT/SomaScan data has relatively large missingness. Our Soft Impute CV module, does well, gives around 70% variance explained in imputed data.
  - The SoftImpute CV module selects a regularization parameter based on the observed data
  - This simplifies our lives because this means that any statistical module we make can assume no missing data
  - You need >30 samples

- Nicole (Austin's wife) is a proteomicist, her thesis was on 6 samples. She separated into transmembrane vs  non proteins and dropped missing values

- POE & Domain Adaptation: We need matrix methods, deep neural networks aren't the best bet. He has been working on the fact that emprical covariance matrix estimation is not good. Ilha will estimate 15 or so covariance matrix estimation methods. You take a whole bunch of experiments, create a mapping to a common mean and covariance matrix, then future experiments can also be mapped into that space / projected into mapping into that space.
  - He is also making methods to characterize performance. Will be useful for diagnoses as well.

- He is also looking at singular value shrinkage methods. 

- Why he did PPCA: You could put in an option to either plot to the first 2 principal components or the first 2 that have nothing to do with race. This would be useful for Erik Johnson's denoising work.

**Comment by akotlar** [comment]
# 2024-04-30

## Proteomics Topic Meeting
Domain Adaptation:
- Goal is to learn a function that adjusts 1 dataset to match the mean and covariance matrix of the group
- Austin recommends that we find the means and covariances of all batches align, most outlier detection depends on first 2 moments. Estimating the variance in high dimensions is difficult, so we need to regularize the covariance matrix. The problem is we don't have enough samples to do the mapping and evaluate performance. There is no way to way to evaluate on real data.
  - What would the minimum size be? Several thousand samples.
- We have demonstrated that we get good performance on synthetic data. 
- The data we have is ~330 samples, the same samples. We should ask them for their 900 TMT dataset. 9000 proteins, all brain. Accessing this data is a bit easier because it is less identifiable. Thomas will email Nick and ask to get this.
- Have we compared to TAMPOR?
  - There is not a good way to compare to TAMPOR. The way to do this in ML is to use cross validation.
- How was TAMPOR evaluated? Not very rigorously; e.g. they look at the differential expression signal, and see whether it seems right.
- We could intentionally put some outlier point and see if we can detect it. There are 2 modes of running the mass spec, MS2 and MS3. We have a dataset, where they generated the data that had a mixture of MS2 and MS3 (400 samples, 93 or so were MS3). They re-ran the entire dataset, in just MS2

**Comment by akotlar** [comment]
# 2024-05-03

## Proteomics topic meeting
[ProteomicsPipelineDemonstration.ipynb.zip](https://github.com/bystrogenomics/bystro/files/15204105/ProteomicsPipelineDemonstration.ipynb.zip)
- @akotlar is working on adapting this to proteomics data

**Comment by akotlar** [comment]
# 2025-05-08

Austin - working on NeurIPS  paper
Dennis - wrapping up installation guide
Cristina - PR'ing PRS today
Ilha - close to completing the singular value shrinkers; working on operator norm shrinker that is well suited for large n; genotyping data will use the non-negative covariance matrix estimator
Alex - Gotten the 300 sample data decompressed (required 7zip to avoid the "corruption" and refusal to decompress). In comm with Eric Dammers, who has instructed on what the files mean (same naming scheme as the the olink/tmt/somascan paper)

**Comment by akotlar** [comment]
# 2025-05-10 Weekly Meeting

### Agenda
- Create an item in the task list if the work being undertaken is over 1/2 days of work; help us track new and necessary work that comes up post-sprint planning.
