### ISSUE TITLE
Sprint 14 Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#536]
Proteomics:
- [x] Send demonstration for SPPCA @austinTalbot7241993 
- [ ] (stretch) Follow Eric Dammer's pipeline @akotlar 
- [ ] (stretch) Replace Eric Dammer's network analysis with SPPCA and compare @akotlar 
- [x] CITI training to get genotyping data for pQTLs @akotlar @cristinaetrv 

PRS-CS:
- [ ] Imputation model, finish comparing to Minimac4 @austinTalbot7241993 
- [ ] Take in ancestry PCs/Take in GWAS summary statistics as PRS-CS covariates @akotlar 

PRS LD Clumping + Thresholding v2:
- [x] Get remaining LD Maps for missing populations: BEB, ESN, GWD, ITU, MSL (MKK doesn't exist in our 26 populations outputted by the ancestry module), PJL, STU @cristinaetrv 7/8/2024
- [x] If top pop missing, choose next best population @akotlar 
- [x] Liftover AD harmonized scores to hg19 @cristinaetrv 7/10/2024
- [x] Liftover LD Maps to hg19 @cristinaetrv 7/17/2024
- [ ] Incorporate QC steps: FST, sex check, missingness @cristinaetrv 7/17/2024
- [x] Webapp: Need to make sure ancestry, indexing runs before PRS @akotlar 
- [ ] Webapp: expose dropdown for other conditions and studies, add covariate support and expose customization of the covariate support (this is a big one, will be broken down) @akotlar 
- [ ] Webapp: Subject mapping re-enablement and threading through PRS @akotlar 
- [x] (stretch): Average PRS scores over LD clumps of all populations in superpopulation (in case of the superpopulation being directly specified) @akotlar 
- [x] Webapp: Better state handling of job progress @akotlar 

Ancestry V2:
- [ ] Webapp: Color code by superpopulation
- [ ] Webapp: Color code by population

Ancestry V2 (post subject mapping integration):
- [ ] Webapp: Expose ability to set expected superpopulation and compare in the ancestry score section
- [ ] Webapp: Color code by case-control
- [ ] (stretch) Webapp: flag samples that have different superpopulation than specified covariate superpopulation

POE module: 
- [x] Need to add BCA (bias corrected through bootstrap and accelerated (jack knife)) @austinTalbot7241993 7/12/2024
- [x] Covariance tests, want 3 methods fully functional @austinTalbot7241993 
- [x] Test numba jit to speed up @austinTalbot7241993 7/2/2024
- [x] Update Mike E on progress @austinTalbot7241993 7/3/2024
- [x] (stretch) Draft of paper by end of July @austinTalbot7241993 

ML library: 
- [x] Complete domain adaptation and test
- [ ] Start doing extra models (Gaussian mixture model)

### Backlog for Sprint 15
- [ ] PRS: Add support for phenotype in covariates data, and use that to choose the best PRS score (different LD maps) based on variance explained metric. Also output the variance explained and odds ratios.
- [ ] Scheduler (API server, workers): 1) Add more test coverage for the various scheduler functions (I've already added the most important tests).
- [x] Scheduler (API server, workers): 2) Have job submission messages not live as long (currently 48 hours), and have the perl workers periodically touch() them to increase their lifespan. This will make jobs be released faster, enabling them to be rescheduled more quickly (right now they get rescheduled after something like a day, and the user may not realize that they will ever get finished), and will also allow for jobs that take longer than 2 days to complete. - done in https://github.com/bystrogenomics/bystro/pull/545

**Comment by akotlar** [comment]
# 2024-07-12 Sync Meeting
## PRS-CS
Imputation in Python is done, 75% complete Rust module delivered to @akotlar
[genotype_imputation.rs.zip](https://github.com/user-attachments/files/16198378/genotype_imputation.rs.zip). Now @akotlar to link to Python through Maturin/PyO3 and make sure it works. Will work with @austinTalbot7241993 

We can already take covariates, just need to wrap it into Python and feed through UI which is on @akotlar - will be next sprint

## POE module
1000x faster than POIROT, so we don't need JIT. We will pre-compute permutations for specific MAFs. Do the permutation test once, to get the p-values under null, and the actual effect estimates are also 1000x faster than POIROT, are very quick, so don't add much to runtime overall.

**Comment by akotlar** [comment]
# 2024-07-17

## Alex 
Finishing up somascan join to annotation + threading through covariates

## Ilha
Finishing covariance hypothesis testing


## Austin
This week is finishing draft (@akotlar needs to go through it by 2024-07-19). Goal is to get it posted by end of next week.

## Cristina
Checking over on lifted over sumstats (hg19) file, may not be compressed.
Finishing reading last year's grant and looking up resources Thomas.
