### ISSUE TITLE
Sprint 15 Task List

### ISSUE THREAD

**Issue by cristinaetrv** [bystrogenomics/bystro#549]
For August 8 Demo
Goal: Finish improvements that ADRC are looking for 
- [ ] Share only some samples/subjects
- [x] PRS with Dave's results
- [x] Summarize APOE clinical genotypes (get APOE E4/E4, E2/E2, etc per sample)

Annotation
- [x] Give ETA to Dave/Greg Gibson/IBDGC on annotation changes:  

Proteomics
Goals: Get user story, talk to more users (UI standpoint)

- [ ] Follow Eric Dammer's pipeline using DA denoiser @akotlar
- [ ] Replace Eric Dammer's network analysis with SPPCA and compare @akotlar
- [ ] Support pulling prot data from Bystro cluster @akotlar 
- [ ] Document pulling prot data from Bystro cluster @akotlar 
- [ ] Start contacting more proteomicists for UI ideas @akotlar 
- [ ] Read papers on multi-modal analysis (pQTLs etc) @cristinaetrv @akotlar 
- [ ] Determine what Bystro multi-modal analysis will look like by 7/29 @cristinaetrv @akotlar 

Subject mapping

- [ ] Select fields to correspond with Bystro analysis module conventions
- [ ] Add ability to specify whether variables like phenotypes are continuous or categorical @akotlar 

PRS

- [ ] (Backlog) Imputation method, write python bindings and have Rust code compile and be callable from python @akotlar 
- [ ] (Backlog)Take in ancestry PCs/Take in GWAS summary statistics as PRS-CS covariates @akotlar
- [x] Harmonized summary stats for IBD in our format @cristinaetrv 7/25/24
- [x] Lift over harmonized summary stats to hg19 @cristinaetrv 7/25/24
- [x] Rerun Dave's version of PRS with IBD stats to compare with IBD on our version @cristinaetrv 7/25/24
- [x] Calculate odds ratios using threaded through covariate information @akotlar 7/26/24
- [x] UI improvements for advanced settings @akotlar 

Ancestry V2 (post subject mapping integration):

- [ ] Webapp: Expose ability to set expected superpopulation and compare in the ancestry score section
- [ ] Webapp: flag samples that have different superpopulation than specified covariate superpopulation

Infrastructure

- [x] Investigate how difficult integrating existing imputation method as an optional step before annotation @akotlar 
- [ ] Add test coverage for submission functions, progress message updates (queue server responding to submitting events) @akotlar 
- [ ] Add user management ie change password, add S3 bucket, delete account, etc
- [x] Documentation on APIs for GIN deployment @akotlar 7/29/24

POE

- [x] Mike E lab (Taylor) runs on UK Biobank
- [x] Finish BCA (bias corrected method) @austinTalbot7241993 8/2/2024
- [x] Experiments and benchmarking after we get feedback from Mike E @austinTalbot7241993 
- [x] Jupyter notebook tutorial for how to run the method @IlhaH 8/7/24

Hypothesis testing

- [x] Write up draft of paper @IlhaH @austinTalbot7241993 
- [x] Reading papers about hypothesis testing @IlhaH 7/26/24
- [x] Converting hypothesis testing methods from R to python @IlhaH 
- [x] Share overleaf link of draft @austinTalbot7241993 7/23/24
- [x] Talk to Xiucai about where paper should be submitted, which methods should we incorporate, how to test behavior 7/29/2024
- [x] Send Xiucai summary documents 8/6/24

Covariance Matrix Estimation Method

- [x] Write up description of method, benchmarking information, document how to use (paper format) as a supplement for POE @IlhaH 8/8/24
 
Future work (next sprint or later)

- [ ] Run fine-grained compute for Bystro cluster (Ray) in Q3
- [ ] Enable VCF combine by sample in Q3

Grant drafts

- [x] Specific aims (1 page) @akotlar @cristinaetrv 
- [x] Project narrative (3 sentences) @cristinaetrv 
- [x] Project summary (30 lines) @cristinaetrv 
- [x] Research strategy (6 pages) @cristinaetrv 
- [x] Budget (no stated limit) @akotlar 
- [x] Facilities and other resources (no stated limit) @cristinaetrv 
- [x] Resource sharing plans (no stated limit) @cristinaetrv
